# trying to setup _config.yml file. Let's hope this works!
title: My Blog
description: My thoughts, tutorials, and updates.

theme: jekyll-theme-minimal
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme


